import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/Components/Shared/Footer";
import Navbar from "@/Components/Shared/Navbar";

export const metadata: Metadata = {
  title: "PatShop App",
  description: "Generated by PatShop App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <Navbar />
        <hr className="border border-[#D9D9D9]"/>
        <main className=" bg-white text-black">
           {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
