import type { Metadata } from "next";
import { Lora} from "next/font/google";
import "./globals.css";

import Footer from "@/Components/Shared/Footer";
import Navbar from "@/Components/Shared/Navbar";

const lora = Lora({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PatShop App",
  description: "Generated by PatShop App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} antialiased`}
      >
        <Navbar />
        <hr />
        <main>
           {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
